version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: test-app-redis
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: test-app-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
