apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Jaeger
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    jsonData:
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger-tracing

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-logs
    jsonData:
      derivedFields:
        - datasourceUid: jaeger-tracing
          matcherRegex: "trace_id=([0-9a-f]+)"
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
